[build]
  publish = "src/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/health"
  status = 200

